class ContentService {
  constructor() {
    this.content = `
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam luctus augue id neque convallis, eu tempus quam suscipit. Vivamus accumsan fermentum interdum. Phasellus vitae tellus justo. Sed interdum libero lacinia viverra egestas. Praesent tincidunt orci a nisi tempor consectetur. Integer tincidunt, magna eu porttitor ultrices, nisi mauris ultricies lorem, a vulputate purus nisi id justo. Curabitur quis velit fringilla, rutrum mauris quis, dictum dui. Cras bibendum nulla ipsum, sit amet luctus dui cursus aliquam. Donec eleifend leo non consequat varius. Nam tortor lacus, rutrum a arcu eget, tempus ultricies odio. Duis gravida erat sed dolor hendrerit, ac sagittis dui pretium. Nam et suscipit purus, et vehicula purus. Ut a malesuada massa.</p>
        <p>Donec egestas, ex vel hendrerit iaculis, dui est mattis elit, eget faucibus nulla est ut neque. Aliquam erat volutpat. Fusce erat tortor, sagittis sit amet pellentesque vitae, vestibulum ac erat. Donec magna dui, euismod ut cursus eu, blandit ut felis. Sed dapibus, eros in feugiat imperdiet, urna diam faucibus est, id semper ante nulla et arcu. Sed lorem velit, ornare eget sapien ac, fringilla porttitor turpis. Suspendisse potenti. Maecenas pharetra at elit vitae pellentesque. Fusce et dictum libero. Cras vestibulum at odio hendrerit auctor. Ut varius iaculis arcu, id sagittis mi fermentum non.</p>
        <p>In sit amet congue nunc. Etiam sit amet velit vitae est elementum porta. Proin nec ultrices enim. Donec ultrices, est eget venenatis volutpat, nulla neque porttitor enim, in pharetra lectus arcu et odio. Aenean eget faucibus augue. Ut rhoncus porttitor est, pretium consequat arcu pulvinar in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas convallis nunc vel auctor tincidunt. Fusce tellus mauris, dapibus sed sollicitudin eget, pulvinar euismod quam. In varius condimentum vestibulum. Ut pretium orci risus, at aliquam ligula tincidunt bibendum. Phasellus eget nibh lorem.</p>
        <p>Vivamus est magna, ultrices sed scelerisque in, vehicula at libero. In sodales molestie cursus. Vivamus non pellentesque nulla. Aenean in augue velit. Nullam sed mi fermentum, rutrum tortor at, pellentesque leo. Praesent quam lacus, tincidunt ut dapibus eget, feugiat vel dolor. Nulla a est dictum, tristique metus eu, eleifend tellus. Vestibulum odio lorem, condimentum eget tincidunt vitae, consequat sit amet eros. Proin ut lobortis massa. Fusce vel erat porttitor libero finibus pretium sit amet fringilla lorem. Aenean et tempus massa, at malesuada dui. Nulla sed maximus leo, at sagittis nisi. Vestibulum sed facilisis nunc, eget auctor justo. Donec eget nulla eget est scelerisque euismod.</p>
        <p>Vivamus varius, erat in dictum vehicula, magna libero ornare tortor, eget rhoncus nulla quam vitae arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec elementum interdum ipsum, sit amet facilisis turpis aliquam sed. In hac habitasse platea dictumst. Cras lacinia, nisi vel convallis feugiat, est leo laoreet turpis, in eleifend leo nisl quis nulla. Curabitur semper ipsum a risus ullamcorper maximus. Donec nec risus facilisis, maximus augue sit amet, egestas tellus. Morbi suscipit, sem at pellentesque facilisis, sapien urna porttitor erat, at iaculis diam nunc accumsan justo. Maecenas eleifend mollis eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed nisi mauris, condimentum eget turpis sit amet, cursus maximus purus. Duis non elementum felis, vitae convallis risus. Phasellus rutrum nunc ipsum, at eleifend dolor laoreet sed. Duis id tellus tellus. Sed in purus in enim venenatis bibendum sit amet sed dui. Sed rhoncus aliquet eros, ullamcorper vulputate est.</p>
    `;
  }

  async getContent() {
    return new Promise(resolve => resolve(this.content));
  }
}

module.exports.ContentService = ContentService;
